#include <stdio.h>

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

até 4 milhões, soma dos números pares.

*/

int main() {

    int sum = 0;
    int primeiro = 1;
    int segundo = 2;
    int max = 4000000;
    int proximo = 0;

    while ( proximo < max) {

        proximo = primeiro + segundo;
        primeiro = segundo;
        segundo = proximo;

        if (proximo%2 != 0) continue;
        else sum += proximo;

    }

    printf("O resultado da soma dos elementos de Fibonacci pares até quatro milhões é %d.\n", sum);
    return sum;

}
